export const OPENAI_API_KEY = process.env.EXPO_PUBLIC_OPENAI_API_KEY || "";
export const LOCAL_RELAY_SERVER_URL = process.env.EXPO_PUBLIC_LOCAL_RELAY_SERVER_URL || "";
export const QUERY_MESSAGES_URL = process.env.EXPO_PUBLIC_QUERY_MESSAGES_URL || "";
export const GENERAL_BOT_REALTIME_URL = process.env.EXPO_PUBLIC_GENERAL_BOT_REALTIME_URL || "";